
platform :ios, '8.0'
#use_frameworks!

target "SyLiveDemo" do

#      pod 'SyLiveSDK', :git => 'https://github.com/shouyintv/SyLiveSDK_iOS.git’, :tag => 'v0.1.1'
      pod 'SyLiveSDK', :path => '../..'

end

